/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : string,
  'customerName' : string,
  'productId' : string,
  'email' : string,
  'address' : string,
  'timestamp' : Time,
  'quantity' : bigint,
  'phone' : string,
}
export interface PaymentSettings { 'instructions' : string, 'upiId' : string }
export interface Product {
  'id' : string,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'category' : string,
  'priceINR' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<[string, string, number, string], string>,
  'getAllOrders' : ActorMethod<[Principal], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBestSellers' : ActorMethod<[], Array<Product>>,
  'getPaymentSettings' : ActorMethod<[], PaymentSettings>,
  'getProductForCustomer' : ActorMethod<[string], Product>,
  'placeOrder' : ActorMethod<
    [string, string, string, string, string, bigint],
    string
  >,
  'setPaymentSettings' : ActorMethod<[string, string], undefined>,
  'updateProductStock' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];