/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'productId' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'phone' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'priceINR' : IDL.Float64,
});
export const PaymentSettings = IDL.Record({
  'instructions' : IDL.Text,
  'upiId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBestSellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
  'getProductForCustomer' : IDL.Func([IDL.Text], [Product], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'setPaymentSettings' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateProductStock' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'productId' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'priceINR' : IDL.Float64,
  });
  const PaymentSettings = IDL.Record({
    'instructions' : IDL.Text,
    'upiId' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBestSellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getPaymentSettings' : IDL.Func([], [PaymentSettings], ['query']),
    'getProductForCustomer' : IDL.Func([IDL.Text], [Product], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'setPaymentSettings' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateProductStock' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };